from .user_login import router as login_router
from .products_get import router as get_products_router
from .user_signup import router as signup_router
from .me import router as me_router
from .admin import router as admin_router
from .product_create import router as create_product_router
from .product_delete import router as delete_product_router
from .product_update import router as update_product_router
from .home_route import router as route
from .cart_get import router as cart
from .cart_create import router as create_cart_router
from .cart_patch import router as patch_cart_router
from .cart_delete import router as delete_cart_router