"""add_is_visible_to_drops

Revision ID: 02e80a1a09bf
Revises: 5fa384d9642e
Create Date: 2026-07-05 15:51:31.318720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e80a1a09bf'
down_revision: Union[str, Sequence[str], None] = '5fa384d9642e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drops', sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drops', 'is_visible')
    # ### end Alembic commands ###
