"""update int datatype to numeric in order_item, order, product and added product name, images and price column to drop

Revision ID: 40f0c4811c53
Revises: b9c2a617696a
Create Date: 2026-07-04 14:12:28.389824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f0c4811c53'
down_revision: Union[str, Sequence[str], None] = 'b9c2a617696a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drops', 'product_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.add_column('entries', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'address')
    op.alter_column('drops', 'product_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###
