"""add drops system

Revision ID: 7f501cc6a259
Revises: 6165c3ab4689
Create Date: 2026-06-25 17:35:50.261485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f501cc6a259'
down_revision: Union[str, Sequence[str], None] = '6165c3ab4689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drops',
    sa.Column('drop_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('drop_inventory', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('drop_id')
    )
    op.create_index(op.f('ix_drops_drop_id'), 'drops', ['drop_id'], unique=False)
    op.create_table('entries',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('drop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.drop_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('entry_id'),
    sa.UniqueConstraint('drop_id', 'user_id', name='unique_entry_and_user')
    )
    op.create_index(op.f('ix_entries_drop_id'), 'entries', ['drop_id'], unique=False)
    op.create_index(op.f('ix_entries_entry_id'), 'entries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_entries_ranking'), 'entries', ['ranking'], unique=False)
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expiry_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.entry_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('reservation_id'),
    sa.UniqueConstraint('entry_id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_reservations_reservation_id'), 'reservations', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_unique_constraint('unique_user_product', 'cart_items', ['user_id', 'product_id'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('unique_user_product', 'cart_items', type_='unique')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_reservation_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_entries_ranking'), table_name='entries')
    op.drop_index(op.f('ix_entries_entry_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_drop_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_drops_drop_id'), table_name='drops')
    op.drop_table('drops')
    # ### end Alembic commands ###
