"""added address to entrie

Revision ID: b9c2a617696a
Revises: 7e4f6f2e4708
Create Date: 2026-07-04 13:43:38.318131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c2a617696a'
down_revision: Union[str, Sequence[str], None] = '7f501cc6a259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drops', 'product_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.add_column('entries', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'address')
    op.alter_column('drops', 'product_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###
