"""add_device_fingerprint_to_entries

Revision ID: ceff8b624bdb
Revises: c3a8f2e91d47
Create Date: 2026-08-11 02:13:03.949166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ceff8b624bdb'
down_revision: Union[str, Sequence[str], None] = 'c3a8f2e91d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('device_fingerprint', sa.String(), nullable=True))
    op.create_index(op.f('ix_entries_device_fingerprint'), 'entries', ['device_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_device_fingerprint'), table_name='entries')
    op.drop_column('entries', 'device_fingerprint')
    # ### end Alembic commands ###
